{
 "title": "New dashboard-2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Smoke Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "SERVER_STATUS_total{v=\"SMOKE\"}"
    }
   ]
  },
  {
   "title": "Temperature Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "SERVER_STATUS_total{v=\"TEMP\"}"
    }
   ]
  },
  {
   "title": "Heart Beat Sensor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "SERVER_STATUS_total{v=\"HEART\"} "
    }
   ]
  },
  {
   "title": "Humidity Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "SERVER_STATUS_total{v=\"HUMIDITY\"}"
    }
   ]
  },
  {
   "title": "Gauge Meter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SERVER_STATUS_total{v=~\"SMOKE|HEART|HUMIDITY|TEMP\"}",
     "legendFormat": "Heart | Humidity | Smoke | Temperature"
    }
   ]
  },
  {
   "title": "Battery Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SERVER_STATUS_total{v=\"BATTERY\"}"
    }
   ]
  }
 ]
}